global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cloudwatch_exporter'
    static_configs:
      - targets: ['cloudwatch_exporter:9106']