name: deploy/server-cloud-module 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY}}


      - name: Deploy to EC2
        run: |
            ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
              cd /home/ec2-user/server-cloud-Module/server
              git pull origin main
              npm install
              pm2 restart server-cloud-module || pm2 start index.js --name server-cloud-module
            EOF
